(() => {
  const support = 'atmsupportcentre@gmail.com';
  const isEnglish = () => (document.documentElement.lang || '').toLowerCase().startsWith('en');
  const text = (it, en) => isEnglish() ? en : it;
  const knowledge = [
    { keys:['ecosistema','ecosystem','flusso','flow','insieme','suite'], it:'L’ecosistema ATM è composto da tre elementi: ATM Version 7 crea e suddivide le aree; ATM Bridge assiste il trasferimento del GeoJSON verso Territory Helper; ATM Manager organizza territori, persone, richieste, assegnazioni, restituzioni e sicurezza in Space isolati.', en:'The ATM ecosystem has three parts: ATM Version 7 creates and divides areas; ATM Bridge assists GeoJSON transfer to Territory Helper; ATM Manager organizes territories, people, requests, assignments, returns and security inside isolated Spaces.' },
    { keys:['v7','version 7','crea','genera','generate','kml','geojson','confini','boundary'], it:'ATM Version 7 parte da un’area geografica, genera la quantità richiesta di territori, permette di controllare perimetri e risultato sulla mappa, quindi esporta GeoJSON o KML. Apri la pagina dedicata per il flusso completo e l’animazione introduttiva.', en:'ATM Version 7 starts from a geographic area, generates the requested number of territories, lets you review boundaries and results on the map, then exports GeoJSON or KML. Open its dedicated page for the full workflow and intro animation.' },
    { keys:['bridge','estensione','extension','firefox','chrome','plugin','territory helper','trasfer'], it:'ATM Bridge 0.7.3 rileva il GeoJSON pronto, lo conserva temporaneamente nello storage locale del browser, mostra stato e notifica e, dopo la conferma, apre o riusa la scheda di Territory Helper. È pubblico su Firefox; su Chrome desktop si installa manualmente dal pacchetto ZIP.', en:'ATM Bridge 0.7.3 detects the ready GeoJSON, temporarily keeps it in browser local storage, shows status and a notification and, after confirmation, opens or reuses the Territory Helper tab. It is public on Firefox; Chrome desktop uses the manual ZIP package.' },
    { keys:['manager','space','spazi','ruoli','role','admin','utente','user','assegn','richiest','resting'], it:'ATM Manager è il centro operativo. Ogni Space isola persone e dati. I ruoli applicano permessi diversi; richieste, assegnazioni, restituzioni, periodi di riposo e registro attività costruiscono una cronologia controllabile. MFA, passkey e notifiche completano il flusso di sicurezza.', en:'ATM Manager is the operating center. Each Space isolates people and data. Roles apply different permissions; requests, assignments, returns, resting periods and the activity log build an auditable history. MFA, passkeys and notifications complete the security flow.' },
    { keys:['sicurezza','security','privacy','dati','data','password','supabase','rls','mfa','passkey'], it:'Sicurezza e privacy: gli Space sono separati tramite controlli applicativi e policy RLS; le operazioni sensibili richiedono il ruolo corretto e, dove previsto, una sessione MFA verificata. Le chiavi privilegiate non devono essere esposte nel browser. Questa guida pubblica non accede a Supabase, account, password, file o sessioni.', en:'Security and privacy: Spaces are separated through application controls and RLS policies; sensitive operations require the correct role and, where configured, a verified MFA session. Privileged keys must never be exposed in the browser. This public guide cannot access Supabase, accounts, passwords, files or sessions.' },
    { keys:['permessi','permission','tabs','storage','notifiche','notification'], it:'ATM Bridge richiede storage, tabs, scripting, unlimitedStorage e notifications per mantenere il trasferimento in sospeso, trovare o aprire le pagine supportate e avvisare l’utente. Gli host dichiarati sono ATM v7, gli ambienti locali di sviluppo e Territory Helper. Il manifest Firefox dichiara raccolta dati richiesta: “none”.', en:'ATM Bridge requests storage, tabs, scripting, unlimitedStorage and notifications to keep pending transfers, find or open supported pages and notify the user. Declared hosts are ATM v7, local development environments and Territory Helper. The Firefox manifest declares required data collection: “none”.' },
    { keys:['install','scarica','download','mobile','telefono','tablet'], it:'Firefox desktop: usa la pagina ufficiale Add-ons. Chrome desktop: scarica lo ZIP, estrailo, apri chrome://extensions, abilita Modalità sviluppatore e usa “Carica estensione non pacchettizzata”. Il flusso dell’estensione è progettato per browser desktop, non per Chrome mobile.', en:'Firefox desktop: use the official Add-ons page. Chrome desktop: download and extract the ZIP, open chrome://extensions, enable Developer mode and choose “Load unpacked”. The extension workflow targets desktop browsers, not Chrome mobile.' },
    { keys:['email','supporto','support','aiuto','help','problema','bug'], it:`Per assistenza scrivi a ${support}. Indica prodotto, browser, dispositivo, passaggi eseguiti e messaggio di errore; non inviare password, codici OTP o chiavi API.`, en:`For support email ${support}. Include product, browser, device, steps and the error message; never send passwords, OTP codes or API keys.` },
    { keys:['ai','assistente','assistant','come funzioni','how do you work'], it:'Sono la guida pubblica dell’ecosistema ATM. Rispondo da una knowledge base locale e verificata: non chiamo servizi AI esterni, non leggo account e non vedo i tuoi dati. Se un’informazione non è documentata, ti indirizzo al supporto invece di inventarla.', en:'I am the public ATM ecosystem guide. I answer from a verified local knowledge base: I do not call external AI services, read accounts or see your data. If something is not documented, I direct you to support instead of inventing it.' }
  ];
  const markup = `<button class="atm-guide-launcher" aria-label="${text('Apri la guida ATM','Open ATM guide')}"><span>${text('Chiedi alla guida ATM','Ask the ATM guide')}</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3a7 7 0 0 0-7 7v1a5 5 0 0 0 5 5h1l4 3v-3a5 5 0 0 0 4-5v-1a7 7 0 0 0-7-7Z"/><path d="M9 10h.01M12 10h.01M15 10h.01"/></svg></button><div class="atm-guide-shell" aria-hidden="true"><section class="atm-guide" role="dialog" aria-modal="true" aria-label="ATM Ecosystem Guide"><header class="atm-guide-head"><div class="atm-guide-face"><video autoplay muted loop playsinline><source src="assets/ai-animation-flow-1.mp4" type="video/mp4"></video><div class="atm-guide-fallback"><b>AI</b></div></div><div class="atm-guide-title"><b>ATM Ecosystem Guide</b><small>${text('Conoscenza pubblica verificata · nessun accesso ai dati','Verified public knowledge · no data access')}</small></div><button class="atm-guide-close" aria-label="${text('Chiudi','Close')}">×</button></header><div class="atm-guide-feed"><div class="atm-guide-message bot">${text('Ciao. Conosco il flusso ATM dalla creazione alla gestione. Chiedimi di ATM v7, Bridge, Manager, installazione, dati o sicurezza.','Hello. I know the ATM workflow from creation to management. Ask about ATM v7, Bridge, Manager, installation, data or security.')}</div><div class="atm-guide-chips"><button class="atm-guide-chip">ATM Version 7</button><button class="atm-guide-chip">ATM Bridge</button><button class="atm-guide-chip">ATM Manager</button><button class="atm-guide-chip">${text('Sicurezza e dati','Security & data')}</button></div></div><form class="atm-guide-form"><input class="atm-guide-input" autocomplete="off" maxlength="300" placeholder="${text('Scrivi una domanda…','Ask a question…')}" aria-label="${text('Domanda','Question')}"><button class="atm-guide-send" aria-label="${text('Invia','Send')}">↑</button><small class="atm-guide-note">${text('Guida informativa locale · non inserire dati riservati','Local information guide · do not enter sensitive data')}</small></form></section></div>`;
  document.body.insertAdjacentHTML('beforeend', markup);
  const launcher=document.querySelector('.atm-guide-launcher'), shell=document.querySelector('.atm-guide-shell'), close=document.querySelector('.atm-guide-close'), feed=document.querySelector('.atm-guide-feed'), form=document.querySelector('.atm-guide-form'), input=document.querySelector('.atm-guide-input'), face=document.querySelector('.atm-guide-face'), video=face.querySelector('video');
  const open=()=>{shell.classList.add('is-open');shell.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),80)};
  const shut=()=>{shell.classList.remove('is-open');shell.setAttribute('aria-hidden','true')};
  launcher.addEventListener('click',open);document.querySelectorAll('[data-open-atm-guide]').forEach(button=>button.addEventListener('click',open));close.addEventListener('click',shut);shell.addEventListener('click',e=>{if(e.target===shell)shut()});document.addEventListener('keydown',e=>{if(e.key==='Escape')shut()});
  video.addEventListener('error',()=>face.classList.add('video-missing')); if(video.readyState===0) setTimeout(()=>{if(video.error||video.networkState===3)face.classList.add('video-missing')},1200);
  const add=(value,who)=>{const node=document.createElement('div');node.className=`atm-guide-message ${who}`;node.textContent=value;feed.appendChild(node);feed.scrollTop=feed.scrollHeight};
  const answer=q=>{const normalized=q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');let best=null,score=0;for(const item of knowledge){const current=item.keys.reduce((n,k)=>n+(normalized.includes(k.normalize('NFD').replace(/[\u0300-\u036f]/g,''))?1:0),0);if(current>score){score=current;best=item}}return best?(isEnglish()?best.en:best.it):text(`Non trovo una risposta verificata per questa domanda. Scrivi a ${support}: ti aiuteremo senza chiederti dati riservati.`,`I do not have a verified answer for that question. Email ${support}; we will help without asking for sensitive data.`)};
  const ask=q=>{if(!q.trim())return;add(q.trim(),'user');setTimeout(()=>add(answer(q),'bot'),180)};
  form.addEventListener('submit',e=>{e.preventDefault();const q=input.value;input.value='';ask(q)});document.querySelectorAll('.atm-guide-chip').forEach(c=>c.addEventListener('click',()=>ask(c.textContent)));
})();
