const translations={
  it:{navExperience:"Esperienza",openApp:"Apri ATM",eyebrow:"La nuova generazione è qui",heroCopy:"ATM Territory Maker Version 7 trasforma la creazione dei territori in un flusso chiaro, veloce e sorprendentemente semplice.",launchV7:"Avvia Version 7",discover:"Scopri l’esperienza",previewTitle:"I tuoi territori",territories:"Territori",coverage:"Copertura",ready:"Pronti",experienceLabel:"L’esperienza",statement:"Meno complessità.<br>Più territorio.",statementCopy:"Un ambiente focalizzato che mette gli strumenti importanti al posto giusto. Tutto ciò che serve per costruire, verificare e preparare il lavoro.",featureCreate:"Crea con precisione",featureCreateCopy:"Disegna, organizza e rifinisci territori mantenendo una visione chiara del risultato.",featureTransfer:"Trasferisci senza attrito",featureTransferCopy:"ATM Bridge accompagna il file GeoJSON verso Territory Helper con un flusso guidato.",featureResponsive:"Progettato per adattarsi",featureResponsiveCopy:"Un’interfaccia reattiva e leggibile, dal desktop ai display touch.",bridgeTitle:"Il passaggio finale,<br>reso naturale.",bridgeCopy:"ATM Bridge collega ATM Territory Maker a Territory Helper. Riconosce il territorio pronto, prepara il trasferimento e ti mantiene sempre in controllo.",discoverBridge:"Scopri ATM Bridge",continueHelper:"Continua su Territory Helper",builtAround:"Costruita intorno",yourFlow:"al tuo flusso.",readyQuestion:"Pronto a creare il prossimo territorio?",startNow:"Inizia con Version 7.",openATM:"Apri ATM Territory Maker",support:"Supporto"},
  en:{navExperience:"Experience",openApp:"Open ATM",eyebrow:"The next generation is here",heroCopy:"ATM Territory Maker Version 7 turns territory creation into a clear, fast and remarkably simple workflow.",launchV7:"Launch Version 7",discover:"Discover the experience",previewTitle:"Your territories",territories:"Territories",coverage:"Coverage",ready:"Ready",experienceLabel:"The experience",statement:"Less complexity.<br>More territory.",statementCopy:"A focused environment that puts the important tools exactly where they belong. Everything you need to build, review and prepare the work.",featureCreate:"Create with precision",featureCreateCopy:"Draw, organize and refine territories while keeping a clear view of the result.",featureTransfer:"Transfer without friction",featureTransferCopy:"ATM Bridge guides your GeoJSON file toward Territory Helper through a focused workflow.",featureResponsive:"Designed to adapt",featureResponsiveCopy:"A responsive, readable interface made for desktop and touch displays.",bridgeTitle:"The final step,<br>made natural.",bridgeCopy:"ATM Bridge connects ATM Territory Maker to Territory Helper. It recognizes a ready territory, prepares the transfer and keeps you in control.",discoverBridge:"Discover ATM Bridge",continueHelper:"Continue to Territory Helper",builtAround:"Built around",yourFlow:"your workflow.",readyQuestion:"Ready to create your next territory?",startNow:"Start with Version 7.",openATM:"Open ATM Territory Maker",support:"Support"}
};
let language=localStorage.getItem("atm-showcase-language")||"it";
const button=document.getElementById("languageButton");
function applyLanguage(){document.documentElement.lang=language;button.textContent=language.toUpperCase();document.querySelectorAll("[data-i18n]").forEach(element=>{const value=translations[language][element.dataset.i18n];if(value)element.innerHTML=value});localStorage.setItem("atm-showcase-language",language)}
button.addEventListener("click",()=>{language=language==="it"?"en":"it";applyLanguage()});
applyLanguage();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("in-view")}),{threshold:.15});
document.querySelectorAll(".feature-card,.bridge,.version,.statement").forEach(element=>observer.observe(element));

